@baseUrl = http://127.0.0.1:5000

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

# @name logout
POST {{baseUrl}}/logout
Content-Type: application/json

###

# @name add product
POST {{baseUrl}}/api/products/add
Content-Type: application/json

{
  "name": "Product 1",
  "price": 10.99,
  "description": "This is a product description"
}

###

# @name delete product
DELETE {{baseUrl}}/api/products/delete/1
Content-Type: application/json

###

# @name get product details
GET {{baseUrl}}/api/products/1
Content-Type: application/json

###

# @name update product
PUT {{baseUrl}}/api/products/update/1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 12.99,
  "description": "This is an updated product description"
}

###

# @name get all products
GET {{baseUrl}}/api/products
Content-Type: application/json

###

# @name add product to cart
POST {{baseUrl}}/api/cart/add/1
Content-Type: application/json

###

# @name remove product from cart
DELETE {{baseUrl}}/api/cart/remove/1
Content-Type: application/json
