@baseUrl = http://127.0.0.1:5000

# @name add product
POST {{baseUrl}}/api/products/add
Content-Type: application/json

{
  "name": "Product 3",
  "price": 10.99,
  "description": "This is a product description"
}

###

# @name delete product
DELETE {{baseUrl}}/api/products/delete/1
Content-Type: application/json

###

# @name get product details
GET {{baseUrl}}/api/products/1
Content-Type: application/json

###

# @name update product
PUT {{baseUrl}}/api/products/update/1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 12.99,
  "description": "This is an updated product description"
}